/**
 * Golden corpus generator (`pnpm golden`).
 *
 * Writes one JSON file per request into `validation/golden/`, each recording
 * the request, the solver's answer, and hashes of the two inputs that can
 * change the answer: the boat definition without its calibration block, and
 * the calibration block on its own. A diff in a golden file with unchanged
 * hashes is a solver regression; a diff with a changed calibHash is a refit
 * and is expected.
 *
 * Deliberately generated by `calibration/`, never by `validation/` (ADR 0007:
 * calibration writes, validation only reads).
 */
import { createHash } from 'node:crypto';
import { mkdir, readdir, rm, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import { format, resolveConfig } from 'prettier';
import j70 from '../data/boats/j70.json';
import type {
  BoatDefinition,
  Condition,
  ControlState,
  DockControls,
  Forecast,
  RaceControls,
  SailSet,
} from '../src/core/types';
import { baseDock, baseRace } from '../src/core/shape/base';
import { geometryFor } from '../src/core/solve/equilibrium';
import { optimal } from '../src/core/solve/optimal';
import { trimmed } from '../src/core/solve/trimmed';
import { scoreDockSetups } from '../src/core/solve/dock';

export const PROTOCOL_VERSION = 1;
const DIR = 'validation/golden';

const boat = j70 as unknown as BoatDefinition;
const geom = geometryFor(boat);

/** Fixed condition context for the corpus. prov: assumed, chosen once. */
const SEA_STATE = 1;
const CREW_KG = 300;
const TWS_LIST = [6, 8, 10, 12, 14, 16, 20];

function sha256(value: unknown): string {
  return createHash('sha256').update(JSON.stringify(value)).digest('hex');
}

/** Hash of everything about the boat except the fitted numbers. */
export const boatHash = sha256({ ...boat, calibration: undefined });
export const calibHash = sha256(boat.calibration);

function cond(twsKt: number, twaDeg: number, sailset: SailSet): Condition {
  return { twsKt, twaDeg, seaState: SEA_STATE, crewKg: CREW_KG, sailset };
}

interface Entry {
  name: string;
  request: unknown;
  run: () => unknown;
}

/**
 * The 12 hand-picked control states: the base trim, then the five race
 * controls that drive the shape layer hardest at both stops, then the jib
 * lead at its aft stop. Wide enough to catch a sign flip anywhere in
 * rig -> shape -> ORC tune, small enough to stay under the time budget.
 */
export function trimStates(): { name: string; race: RaceControls }[] {
  const base = baseRace();
  const out = [{ name: 'base', race: base }];
  for (const key of ['backstay', 'mainsheet', 'traveller', 'outhaul', 'vang'] as const)
    for (const end of ['min', 'max'] as const)
      out.push({
        name: `${key}-${end}`,
        race: { ...base, [key]: boat.controls[key][end] } as RaceControls,
      });
  out.push({ name: 'jibLead-max', race: { ...base, jibLead: boat.controls.jibLead.max } });
  return out;
}

/** Three dock setups scored against a two-candidate reference list. */
const DOCK_SETUPS: DockControls[] = [
  { upperTurns: 0, lowerTurns: 0, forestayMm: 0 },
  { upperTurns: 4, lowerTurns: 2, forestayMm: 0 },
  { upperTurns: -3, lowerTurns: -2, forestayMm: 15 },
];
const DOCK_CANDIDATES: DockControls[] = [
  { upperTurns: 0, lowerTurns: 0, forestayMm: 0 },
  { upperTurns: 4, lowerTurns: 2, forestayMm: 0 },
];
const FORECAST: Forecast = {
  minKt: 8,
  likelyKt: 10,
  maxKt: 12,
  seaState: SEA_STATE,
  crewKg: CREW_KG,
};

export function entries(): Entry[] {
  const out: Entry[] = [];
  const dock = baseDock();

  for (const twsKt of TWS_LIST) {
    const pad = String(twsKt).padStart(2, '0');
    const vmg: [string, SailSet, number][] = [
      ['vmgup-jib', 'jib', 45],
      ['vmgdn-asym', 'asym', 150],
    ];
    for (const [label, sailset, seed] of vmg)
      out.push({
        name: `tws${pad}-${label}`,
        request: { fn: 'optimal', dock, condition: cond(twsKt, seed, sailset), optimiseTwa: true },
        run: () => optimal(boat, dock, cond(twsKt, seed, sailset), { optimiseTwa: true }, geom),
      });
    const fixed: [number, SailSet][] = [
      [60, 'jib'],
      [90, 'jib'],
      [120, 'asym'],
    ];
    for (const [twaDeg, sailset] of fixed)
      out.push({
        name: `tws${pad}-twa${twaDeg}-${sailset}`,
        request: {
          fn: 'optimal',
          dock,
          condition: cond(twsKt, twaDeg, sailset),
          optimiseTwa: false,
        },
        run: () => optimal(boat, dock, cond(twsKt, twaDeg, sailset), { optimiseTwa: false }, geom),
      });
  }

  for (const { name, race } of trimStates()) {
    const controls: ControlState = { dock, race };
    const condition = cond(12, 42, 'jib');
    out.push({
      name: `trim-${name}`,
      request: { fn: 'trimmed', controls, condition },
      run: () => trimmed(boat, controls, condition, geom),
    });
  }

  out.push({
    name: 'dock-score',
    request: {
      fn: 'scoreDockSetups',
      setups: DOCK_SETUPS,
      forecast: FORECAST,
      candidates: DOCK_CANDIDATES,
    },
    run: () => scoreDockSetups(boat, DOCK_SETUPS, FORECAST, DOCK_CANDIDATES, geom),
  });

  return out;
}

async function writeJson(file: string, value: unknown): Promise<void> {
  const cfg = await resolveConfig(file);
  const text = await format(JSON.stringify(value, null, 2), {
    ...cfg,
    filepath: file,
    parser: 'json',
  });
  await writeFile(file, text, 'utf8');
}

export async function main(): Promise<void> {
  const t0 = Date.now();
  await mkdir(DIR, { recursive: true });
  // The corpus is the complete set, not an accumulation of past runs: a
  // renamed or dropped request must not leave a stale file behind.
  for (const f of await readdir(DIR)) if (f.endsWith('.json')) await rm(`${DIR}/${f}`);

  const list = entries();
  for (const [i, e] of list.entries()) {
    const file = `${DIR}/${String(i + 1).padStart(3, '0')}-${e.name}.json`;
    await writeJson(file, {
      name: e.name,
      protocolVersion: PROTOCOL_VERSION,
      boatHash,
      calibHash,
      request: e.request,
      result: e.run(),
    });
  }
  console.log(
    `wrote ${list.length} golden files to ${DIR} in ${((Date.now() - t0) / 1000).toFixed(1)} s\n` +
      `  boatHash  ${boatHash}\n  calibHash ${calibHash}`,
  );
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) await main();
