/**
 * Golden corpus generator (`pnpm golden`).
 *
 * Writes `validation/golden/*.json` in the format `validation/README.md`
 * documents and `validation/golden.test.ts` replays: a `cases` array plus the
 * two hashes from `compare.ts`. A diff with unchanged hashes is a solver
 * regression; a stale hash is a recalibration and the replay skips instead of
 * failing.
 *
 * Deliberately generated by `calibration/`, never by `validation/` (ADR 0007:
 * calibration writes, validation only reads).
 */
import { mkdir, readdir, rm, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import { format, resolveConfig } from 'prettier';
import { boat, boatHash, calibHash, POLAR_CREW_KG, POLAR_SEA_STATE } from '../validation/compare';
import type {
  Condition,
  ControlState,
  DockControls,
  RaceControls,
  SailSet,
} from '../src/core/types';
import { baseDock, baseRace } from '../src/core/shape/base';
import { geometryFor } from '../src/core/solve/equilibrium';
import { optimal } from '../src/core/solve/optimal';
import { trimmed } from '../src/core/solve/trimmed';

const DIR = 'validation/golden';
const GEOM = geometryFor(boat);
const TWS_LIST = [6, 8, 10, 12, 14, 16, 20];

interface Case {
  id: string;
  call: 'trimmed' | 'optimal';
  condition: Condition;
  controls?: ControlState;
  dock?: DockControls;
  opts?: { optimiseTwa: boolean };
  result: unknown;
}

function cond(twsKt: number, twaDeg: number, sailset: SailSet): Condition {
  return { twsKt, twaDeg, seaState: POLAR_SEA_STATE, crewKg: POLAR_CREW_KG, sailset };
}

function optimalCase(
  id: string,
  dock: DockControls,
  condition: Condition,
  optimiseTwa: boolean,
): Case {
  const opts = { optimiseTwa };
  return {
    id,
    call: 'optimal',
    dock,
    opts,
    condition,
    result: json(optimal(boat, dock, condition, opts, GEOM)),
  };
}

function trimmedCase(id: string, controls: ControlState, condition: Condition): Case {
  return {
    id,
    call: 'trimmed',
    controls,
    condition,
    result: json(trimmed(boat, controls, condition, GEOM)),
  };
}

/** Round-trip so the recorded value is exactly what the replay will compare. */
function json(v: unknown): unknown {
  return JSON.parse(JSON.stringify(v));
}

/** Every polar-shaped request: VMG up and down, plus the three fixed angles. */
export function polarCases(): Case[] {
  const dock = baseDock();
  return TWS_LIST.flatMap((twsKt) => {
    const pad = String(twsKt).padStart(2, '0');
    return [
      optimalCase(`tws${pad}-vmgup-jib`, dock, cond(twsKt, 45, 'jib'), true),
      optimalCase(`tws${pad}-vmgdn-asym`, dock, cond(twsKt, 150, 'asym'), true),
      optimalCase(`tws${pad}-twa60-jib`, dock, cond(twsKt, 60, 'jib'), false),
      optimalCase(`tws${pad}-twa90-jib`, dock, cond(twsKt, 90, 'jib'), false),
      optimalCase(`tws${pad}-twa120-asym`, dock, cond(twsKt, 120, 'asym'), false),
    ];
  });
}

/**
 * The 12 hand-picked control states: the base trim, then the five race controls
 * that drive the shape layer hardest at both of their stops, then the jib lead
 * at its aft stop. Wide enough to catch a sign flip anywhere in
 * rig -> shape -> ORC tune, small enough to stay inside the time budget.
 */
export function trimStates(): { id: string; race: RaceControls }[] {
  const base = baseRace();
  const out = [{ id: 'base', race: base }];
  for (const key of ['backstay', 'mainsheet', 'traveller', 'outhaul', 'vang'] as const)
    for (const end of ['min', 'max'] as const)
      out.push({
        id: `${key}-${end}`,
        race: { ...base, [key]: boat.controls[key][end] } as RaceControls,
      });
  out.push({ id: 'jibLead-max', race: { ...base, jibLead: boat.controls.jibLead.max } });
  return out;
}

export function trimCases(): Case[] {
  const dock = baseDock();
  const condition = cond(12, 42, 'jib');
  return trimStates().map((s) => trimmedCase(s.id, { dock, race: s.race }, condition));
}

/** Three dock setups across a small forecast: the inputs a dock score is built from. */
const DOCK_SETUPS: { id: string; dock: DockControls }[] = [
  { id: 'base', dock: { upperTurns: 0, lowerTurns: 0, forestayMm: 0 } },
  { id: 'heavy', dock: { upperTurns: 4, lowerTurns: 2, forestayMm: 0 } },
  { id: 'light', dock: { upperTurns: -3, lowerTurns: -2, forestayMm: 15 } },
];

export function dockCases(): Case[] {
  return DOCK_SETUPS.flatMap((s) =>
    [8, 10, 12].flatMap((twsKt) => [
      optimalCase(`${s.id}-tws${twsKt}-up`, s.dock, cond(twsKt, 45, 'jib'), true),
      optimalCase(`${s.id}-tws${twsKt}-dn`, s.dock, cond(twsKt, 150, 'asym'), true),
    ]),
  );
}

async function writeJson(file: string, value: unknown): Promise<void> {
  const cfg = await resolveConfig(file);
  const text = await format(JSON.stringify(value, null, 2), {
    ...cfg,
    filepath: file,
    parser: 'json',
  });
  await writeFile(file, text, 'utf8');
}

export async function main(): Promise<void> {
  const t0 = Date.now();
  await mkdir(DIR, { recursive: true });
  // The corpus is the complete set, not an accumulation of past runs: a renamed
  // or dropped case must not leave a stale file behind.
  for (const f of await readdir(DIR)) if (f.endsWith('.json')) await rm(`${DIR}/${f}`);

  const hashes = { boatHash: boatHash(), calibHash: calibHash() };
  const groups: [string, Case[]][] = [
    ['001-polar-points', polarCases()],
    ['002-trim-states', trimCases()],
    ['003-dock-setups', dockCases()],
  ];
  let n = 0;
  for (const [name, cases] of groups) {
    await writeJson(`${DIR}/${name}.json`, { ...hashes, cases });
    n += cases.length;
  }
  console.log(
    `wrote ${groups.length} golden files (${n} cases) to ${DIR} in ` +
      `${((Date.now() - t0) / 1000).toFixed(1)} s\n` +
      `  boatHash ${hashes.boatHash}  calibHash ${hashes.calibHash}`,
  );
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) await main();
