/**
 * Golden-corpus regression: replay every recorded request through the solver
 * and assert the answer has not moved.
 *
 * The corpus is generated by `pnpm golden` (calibration/golden.ts) and lives
 * in `validation/golden/*.json`. Its shape is documented in
 * `validation/README.md`. Deliberate model changes regenerate it; accidental
 * ones fail here.
 */
import { readdirSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import type { Condition, ControlState, DockControls } from '../src/core/types';
import { geometryFor } from '../src/core/solve/equilibrium';
import { optimal } from '../src/core/solve/optimal';
import { trimmed } from '../src/core/solve/trimmed';
import { boat, boatHash, calibHash } from './compare';

const DIR = fileURLToPath(new URL('./golden', import.meta.url));
const GEOM = geometryFor(boat);
/** Relative closeness on numbers; strings and booleans must match exactly. */
const REL = 1e-6;

interface GoldenCase {
  id: string;
  call: 'trimmed' | 'optimal';
  condition: Condition;
  controls?: ControlState;
  dock?: DockControls;
  opts?: { optimiseTwa: boolean };
  result: unknown;
}

interface GoldenFile {
  boatHash?: string;
  calibHash?: string;
  cases: GoldenCase[];
}

function files(): string[] {
  try {
    return readdirSync(DIR)
      .filter((f) => f.endsWith('.json'))
      .sort();
  } catch {
    return [];
  }
}

const found = files();

describe('golden corpus', () => {
  if (found.length === 0) {
    it.skip('no golden files in validation/golden — run pnpm golden', () => {});
    return;
  }

  const expectedBoat = boatHash();
  const expectedCalib = calibHash();

  for (const name of found) {
    const file = JSON.parse(readFileSync(`${DIR}/${name}`, 'utf8')) as GoldenFile;
    const stale =
      (file.boatHash !== undefined && file.boatHash !== expectedBoat) ||
      (file.calibHash !== undefined && file.calibHash !== expectedCalib);

    if (stale) {
      it.skip(`${name}: recorded against a different boat — run pnpm golden`, () => {});
      continue;
    }

    it(`${name}: ${file.cases?.length ?? 0} cases replay unchanged`, () => {
      expect(Array.isArray(file.cases), `${name}: missing "cases" array`).toBe(true);
      for (const c of file.cases) {
        const got =
          c.call === 'trimmed'
            ? trimmed(boat, need(c.controls, `${name}/${c.id}: controls`), c.condition, GEOM)
            : optimal(
                boat,
                need(c.dock, `${name}/${c.id}: dock`),
                c.condition,
                c.opts ?? { optimiseTwa: true },
                GEOM,
              );
        const diffs = compare(c.result, JSON.parse(JSON.stringify(got)), `${name}/${c.id}`);
        expect(diffs).toEqual([]);
      }
    });
  }
});

function need<T>(v: T | undefined, what: string): T {
  if (v === undefined) throw new Error(`${what} is required (see validation/README.md)`);
  return v;
}

/** Deep closeness: numbers within REL relative, everything else exact. */
function compare(want: unknown, got: unknown, path: string): string[] {
  if (typeof want === 'number' && typeof got === 'number') {
    const tol = REL * Math.max(1, Math.abs(want));
    return Math.abs(want - got) <= tol ? [] : [`${path}: ${want} != ${got}`];
  }
  if (Array.isArray(want) || Array.isArray(got)) {
    if (!Array.isArray(want) || !Array.isArray(got) || want.length !== got.length)
      return [`${path}: array shape differs`];
    return want.flatMap((w, i) => compare(w, got[i], `${path}[${i}]`));
  }
  if (want !== null && got !== null && typeof want === 'object' && typeof got === 'object') {
    const w = want as Record<string, unknown>;
    const g = got as Record<string, unknown>;
    const keys = [...new Set([...Object.keys(w), ...Object.keys(g)])].sort();
    return keys.flatMap((k) =>
      k in w && k in g ? compare(w[k], g[k], `${path}.${k}`) : [`${path}.${k}: only on one side`],
    );
  }
  return Object.is(want, got) ? [] : [`${path}: ${String(want)} != ${String(got)}`];
}
