/**
 * Golden-corpus regression: replay every recorded request through the solver
 * and assert the answer has not moved.
 *
 * The corpus is generated by `pnpm golden --boat <id>` (calibration/golden.ts)
 * and lives in `validation/golden/<id>/*.json`, one directory per class. Its
 * shape is documented in `validation/README.md`. Deliberate model changes
 * regenerate it; accidental ones fail here.
 *
 * Every *registered* class is replayed, not just the default: a second boat
 * whose corpus nobody runs is a corpus that rots. A class with no corpus yet
 * is reported as skipped rather than passing silently.
 */
import { readdirSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import type { Condition, ControlState, DockControls } from '../src/core/types';
import { geometryFor } from '../src/core/solve/equilibrium';
import { optimal } from '../src/core/solve/optimal';
import { trimmed } from '../src/core/solve/trimmed';
import { boatFor, boatIds } from '../src/lib/boat';
import { boatHash, calibHash } from './compare';

const ROOT = fileURLToPath(new URL('./golden', import.meta.url));
/** Relative closeness on numbers; strings and booleans must match exactly. */
const REL = 1e-6;

interface GoldenCase {
  id: string;
  call: 'trimmed' | 'optimal';
  condition: Condition;
  controls?: ControlState;
  dock?: DockControls;
  opts?: { optimiseTwa: boolean };
  result: unknown;
}

interface GoldenFile {
  boatHash?: string;
  calibHash?: string;
  cases: GoldenCase[];
}

function files(dir: string): string[] {
  try {
    return readdirSync(dir)
      .filter((f) => f.endsWith('.json'))
      .sort();
  } catch {
    return [];
  }
}

describe('golden corpus', () => {
  for (const boatId of boatIds()) describeBoat(boatId);
});

function describeBoat(boatId: string): void {
  const dir = `${ROOT}/${boatId}`;
  const found = files(dir);
  const boat = boatFor(boatId);

  describe(boatId, () => {
    if (found.length === 0) {
      it.skip(`no golden files in validation/golden/${boatId} — run pnpm golden --boat ${boatId}`, () => {});
      return;
    }

    const geom = geometryFor(boat);
    const expectedBoat = boatHash(boat);
    const expectedCalib = calibHash(boat);

    for (const name of found) {
      const file = JSON.parse(readFileSync(`${dir}/${name}`, 'utf8')) as GoldenFile;

      // A recalibration is a deliberate re-fit of the knobs, and every number
      // here is expected to move: skipping is the documented behaviour.
      if (file.calibHash !== undefined && file.calibHash !== expectedCalib) {
        it.skip(`${name}: recorded against calibration ${file.calibHash} — run pnpm golden --boat ${boatId}`, () => {});
        continue;
      }

      // A boat-geometry edit is not a recalibration. Skipping one turned the
      // regression net off for two PRs (#79, #80) while `make check` stayed
      // green, so a stale boatHash fails and says how to fix it.
      if (file.boatHash !== undefined && file.boatHash !== expectedBoat) {
        it(`${name}: recorded against boat ${file.boatHash}, current is ${expectedBoat}`, () => {
          throw new Error(
            `${name} was recorded against boat geometry ${file.boatHash} but data/boats/${boatId}.json now hashes to ${expectedBoat}. ` +
              `A geometry edit is not a recalibration: review the intended change, then run \`pnpm golden --boat ${boatId}\` and commit the corpus.`,
          );
        });
        continue;
      }

      it(`${name}: ${file.cases?.length ?? 0} cases replay unchanged`, () => {
        expect(Array.isArray(file.cases), `${name}: missing "cases" array`).toBe(true);
        for (const c of file.cases) {
          const got =
            c.call === 'trimmed'
              ? trimmed(boat, need(c.controls, `${name}/${c.id}: controls`), c.condition, geom)
              : optimal(
                  boat,
                  need(c.dock, `${name}/${c.id}: dock`),
                  c.condition,
                  c.opts ?? { optimiseTwa: true },
                  geom,
                );
          const diffs = compare(c.result, JSON.parse(JSON.stringify(got)), `${name}/${c.id}`);
          expect(diffs).toEqual([]);
        }
      });
    }
  });
}

function need<T>(v: T | undefined, what: string): T {
  if (v === undefined) throw new Error(`${what} is required (see validation/README.md)`);
  return v;
}

/** Deep closeness: numbers within REL relative, everything else exact. */
function compare(want: unknown, got: unknown, path: string): string[] {
  if (typeof want === 'number' && typeof got === 'number') {
    const tol = REL * Math.max(1, Math.abs(want));
    return Math.abs(want - got) <= tol ? [] : [`${path}: ${want} != ${got}`];
  }
  if (Array.isArray(want) || Array.isArray(got)) {
    if (!Array.isArray(want) || !Array.isArray(got) || want.length !== got.length)
      return [`${path}: array shape differs`];
    return want.flatMap((w, i) => compare(w, got[i], `${path}[${i}]`));
  }
  if (want !== null && got !== null && typeof want === 'object' && typeof got === 'object') {
    const w = want as Record<string, unknown>;
    const g = got as Record<string, unknown>;
    const keys = [...new Set([...Object.keys(w), ...Object.keys(g)])].sort();
    return keys.flatMap((k) =>
      k in w && k in g ? compare(w[k], g[k], `${path}.${k}`) : [`${path}.${k}: only on one side`],
    );
  }
  return Object.is(want, got) ? [] : [`${path}: ${String(want)} != ${String(got)}`];
}
