import { describe, expect, it } from 'vitest';
import { leechRibbon, localAoa, luffRibbon, type Ribbon } from './boat';
import {
  ENTRY_DEG,
  JIB_LUFF_STATIONS,
  MAIN_LEECH_STATIONS,
  jibLuffState,
  jibLuffStates,
  leechStates,
} from './telltales';

/**
 * The contract of the extraction (plan `2026-08-28-downwind-fidelity` phase
 * 03): `telltales.ts` must return, per station, exactly the `Ribbon` the plan
 * view computed inline before the move — otherwise the 3D hero and the plan
 * view now agree with each other and both disagree with what shipped.
 *
 * The tables below were generated by running the *pre-refactor* plan-view
 * expressions (`luffRibbon(localAoa(awa, sheet, twist, at), 12)` at ¼ ½ ¾ and
 * the head; `leechRibbon(awa, boom, twist, at)` at ¾ and ½) and pasting the
 * answers, so they are a record of old behaviour rather than a restatement of
 * the new code.
 */

/** awa, sheeting angle, top twist → state at ¼, ½, ¾, head. */
const JIB: [number, number, number, Ribbon[]][] = [
  [24, 10, 8, ['streaming', 'streaming', 'streaming', 'streaming']],
  [24, 4, 4, ['stalled', 'stalled', 'stalled', 'stalled']],
  [20, 20, 14, ['lifting', 'lifting', 'lifting', 'lifting']],
  [35, 12, 10, ['stalled', 'stalled', 'stalled', 'stalled']],
  [45, 20, 18, ['stalled', 'stalled', 'stalled', 'stalled']],
  // Twist enough to carry all three states up one luff: the foot is choking
  // while the head is already lifting. This is the case the 3D hero has to
  // draw per ribbon rather than per sail.
  [32, 15, 24, ['stalled', 'streaming', 'lifting', 'lifting']],
];

/** awa, boom angle, top twist → state at ¾ and ½ of the leech. */
const MAIN: [number, number, number, Ribbon[]][] = [
  [24, 8, 10, ['streaming', 'stalled']],
  [24, 3, 3, ['stalled', 'stalled']],
  [30, 25, 20, ['lifting', 'lifting']],
  [40, 12, 12, ['stalled', 'stalled']],
];

describe('jibLuffStates', () => {
  it('reads the plan view’s four stations, tack to head', () => {
    expect(JIB_LUFF_STATIONS).toEqual([0.25, 0.5, 0.75, 1]);
  });

  it.each(JIB)('awa %d, sheeting %d, twist %d', (awa, sheet, twist, want) => {
    expect(jibLuffStates(awa, sheet, twist).map((t) => t.state)).toEqual(want);
    expect(jibLuffStates(awa, sheet, twist).map((t) => t.at)).toEqual([...JIB_LUFF_STATIONS]);
  });

  it('agrees with the plan view’s own expression at any station', () => {
    // The 3D hero reads its ribbons at the loft's row heights, not at the plan
    // view's four stations, so the equality has to hold off the table too.
    for (const at of [0.1, 0.26, 0.478, 0.739, 0.91]) {
      for (const [awa, sheet, twist] of JIB) {
        expect(jibLuffState(awa, sheet, twist, at)).toBe(
          luffRibbon(localAoa(awa, sheet, twist, at), ENTRY_DEG),
        );
      }
    }
  });
});

describe('leechStates', () => {
  it('reads the top batten before mid-leech, as the plan view drew them', () => {
    expect(MAIN_LEECH_STATIONS).toEqual([0.75, 0.5]);
  });

  it.each(MAIN)('awa %d, boom %d, twist %d', (awa, boom, twist, want) => {
    expect(leechStates(awa, boom, twist).map((t) => t.state)).toEqual(want);
    expect(leechStates(awa, boom, twist).map((t) => t.at)).toEqual([...MAIN_LEECH_STATIONS]);
  });

  it('takes any spar’s sheeting angle, so the jib leech reads the same way', () => {
    const [{ state }] = leechStates(28, 14, 12, [0.5]);
    expect(state).toBe(leechRibbon(28, 14, 12, 0.5));
  });
});
